/*
 * This file is generated by uxsdcxx 0.1.0.
 * https://github.com/duck2/uxsdcxx
 * Modify only if your build process doesn't involve regenerating this file.
 *
 * Cmdline: uxsdcxx/uxsdcxx.py /home/serge/bes/13oct/Backend/OpenFPGA/libs/libopenfpgacapnproto/gen/unique_blocks.xsd
 * Input file: /home/serge/bes/13oct/Backend/OpenFPGA/libs/libopenfpgacapnproto/gen/unique_blocks.xsd
 * md5sum of input file: 1db9d740309076fa51f61413bae1e072
 */
#include "unique_blocks_uxsdcxx.h"

/* All uxsdcxx functions and structs live in this namespace. */
namespace uxsd {


} /* namespace uxsd */
